### ISSUE TITLE
Real-time viability?

### ISSUE THREAD

**Issue by david-courtis** [eth-siplab/UltraInertialPoser#2]
I have a question about the real time performance of the method. What hardware is expected for it to run, and what is the latency of the pipeline on certain hardware configurations?

**Comment by colincqian** [comment]
We run our pipeline on NVIDIA GeForce RTX 3070 and i7-9700K CPU. Our latency is 17ms based on that configuration. If it is without the dynamics optimizer (solely the networks), the latency is 8ms.

**Comment by david-courtis** [comment]
Thanks.
